services:
  bastion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8287:8287"
    environment:
      - BASTION_PORT=8287
      - BASTION_DATABASE_URL=${BASTION_DATABASE_URL}
      - BASTION_JWT_SECRET=${BASTION_JWT_SECRET}
      - BASTION_ADMIN_PASSWORD_HASH=${BASTION_ADMIN_PASSWORD_HASH}
      - BASTION_ADMIN_PASSWORD_SALT=${BASTION_ADMIN_PASSWORD_SALT}
    restart: unless-stopped
